/*
 * File: app/view/DetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DetailPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.detailpanel',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.XTemplate'
    ],

    height: 150,
    itemId: 'detailPanel',
    collapsible: true,
    title: 'Detail',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tpl: [
                '<tpl if="values.id">',
                '    <h3>ID : {id}</h3>',
                '    <h3>Title : {title}</h3>',
                '    <h3>Description : {description}</h3>',
                '    <h3>Date : {date}</h3>',
                '    <h3>isFeatured : {isFeatured}</h3>',
                '</tpl>',
                '',
                '<tpl if="!values.id">',
                '    <h1>Please select a record</h1>',
                '</tpl>'
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    hidden: true,
                    itemId: 'detailToolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'editBtn',
                            icon: 'resources/images/page_white_edit.png',
                            text: 'Edit'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'deleteBtn',
                            icon: 'resources/images/page_white_delete.png',
                            text: 'Delete'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});