/*
 * File: app/view/LayoutSample.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LayoutSample', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.ListPanel',
        'MyApp.view.DetailPanel',
        'MyApp.view.TabPanel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.menu.DatePicker',
        'Ext.menu.Separator',
        'Ext.menu.CheckItem',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.series.Column',
        'Ext.chart.axis.Radial',
        'Ext.chart.series.Radar',
        'Ext.tab.Panel'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    margins: '0 0 5 0',
                    region: 'north',
                    height: 50,
                    itemId: 'headerPanel',
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'menuBtn1',
                                    text: 'Menu1'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'menuBtn2',
                                    text: 'Menu2'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'menuBtn3',
                                    text: 'Menu3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 229,
                    layout: 'card',
                    collapsible: true,
                    title: 'Menu',
                    items: [
                        {
                            xtype: 'treepanel',
                            itemId: 'menuPanel1',
                            store: 'menuStore1',
                            viewConfig: {
                                itemId: 'menuView1'
                            }
                        },
                        {
                            xtype: 'panel',
                            itemId: 'menuPanel2',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'menu',
                                    margins: '5 5 5 5',
                                    floating: false,
                                    itemId: 'menu2_1',
                                    width: 120,
                                    defaultDockWeights: {
                                        top: {
                                            render: 1,
                                            visual: 1
                                        },
                                        left: {
                                            render: 3,
                                            visual: 5
                                        },
                                        right: {
                                            render: 5,
                                            visual: 7
                                        },
                                        bottom: {
                                            render: 7,
                                            visual: 3
                                        }
                                    },
                                    collapsible: true,
                                    title: 'Menu 2-1',
                                    items: [
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-1-1'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-1-2',
                                            menu: {
                                                xtype: 'menu',
                                                itemId: 'menu2_1_2',
                                                width: 120,
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Menu 2-1-2-1'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Menu 2-1-2-2'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Menu 2-1-2-3'
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-1-3',
                                            menu: {
                                                xtype: 'datemenu',
                                                itemId: 'menu2_1_3'
                                            }
                                        },
                                        {
                                            xtype: 'menuseparator'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-1-4'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-1-5'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-1-6'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'menu',
                                    margins: '5 5 5 5',
                                    floating: false,
                                    itemId: 'menu2_2',
                                    width: 120,
                                    collapsible: true,
                                    title: 'Menu 2-2',
                                    items: [
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-2-1'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-2-2'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu 2-2-3'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'menu',
                                    margins: '5 5 5 5',
                                    floating: false,
                                    itemId: 'menu2_3',
                                    width: 120,
                                    collapsible: true,
                                    title: 'Menu 2-3',
                                    items: [
                                        {
                                            xtype: 'menucheckitem',
                                            text: 'Menu 2-3-1'
                                        },
                                        {
                                            xtype: 'menucheckitem',
                                            text: 'Menu 2-3-2'
                                        },
                                        {
                                            xtype: 'menucheckitem',
                                            text: 'Menu 2-3-3'
                                        },
                                        {
                                            xtype: 'menucheckitem',
                                            text: 'Menu 2-3-4'
                                        },
                                        {
                                            xtype: 'menucheckitem',
                                            text: 'Menu 2-3-5'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'menuPanel3',
                            layout: 'accordion',
                            items: [
                                {
                                    xtype: 'treepanel',
                                    title: 'Sub-Menu1',
                                    store: 'subMenuStore1',
                                    rootVisible: false,
                                    viewConfig: {
                                        itemId: 'subMenuView1'
                                    }
                                },
                                {
                                    xtype: 'treepanel',
                                    title: 'Sub-Menu2',
                                    store: 'subMenuStore2',
                                    rootVisible: false,
                                    viewConfig: {
                                        itemId: 'subMenuView2'
                                    }
                                },
                                {
                                    xtype: 'treepanel',
                                    title: 'Sub-Menu3',
                                    store: 'subMenuStore3',
                                    rootVisible: false,
                                    viewConfig: {
                                        itemId: 'subMenuView3'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    margins: '5 0 0 0',
                    region: 'south',
                    height: 50,
                    itemId: 'southPanel'
                },
                {
                    xtype: 'container',
                    region: 'center',
                    itemId: 'centerContainer',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'dashboardContainer',
                            width: 150,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    frame: true,
                                    itemId: 'dashboardPanel1',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            itemId: 'companyGridPanel',
                                            forceFit: true,
                                            store: 'CompanyStore',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'company',
                                                    text: 'Company'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'price',
                                                    text: 'Price'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'revenue',
                                                    text: 'Revenue'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'growth',
                                                    text: 'Growth'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'product',
                                                    text: 'Product'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'market',
                                                    text: 'Market'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 2,
                                    frame: true,
                                    itemId: 'dashboardPanel2',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'chart',
                                            height: 250,
                                            itemId: 'companyChart',
                                            width: 400,
                                            animate: true,
                                            insetPadding: 5,
                                            store: 'CompanyStore',
                                            axes: [
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'price'
                                                    ],
                                                    hidden: true,
                                                    title: 'Numeric Axis',
                                                    minimum: 0,
                                                    position: 'left'
                                                },
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'company'
                                                    ],
                                                    label: {
                                                        renderer: function(v) {
                                                            return Ext.String.ellipsis(v, 15, false);
                                                        },
                                                        font: '9px Arial',
                                                        rotate: {
                                                            degrees: 270
                                                        }
                                                    },
                                                    position: 'bottom'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'column',
                                                    highlight: {
                                                        fill: '#a2b5ca'
                                                    },
                                                    label: {
                                                        contrast: true,
                                                        display: 'insideEnd',
                                                        field: 'price',
                                                        color: '#000',
                                                        orientation: 'vertical',
                                                        'text-anchor': 'middle'
                                                    },
                                                    axis: 'left',
                                                    xField: 'name',
                                                    yField: 'price',
                                                    style: {
                                                        fill: '#a2b5ca'
                                                    },
                                                    listeners: {
                                                        itemmouseup: {
                                                            fn: me.onColumnItemMouseUp,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 2,
                                    frame: true,
                                    itemId: 'dashboardPanel3',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'chart',
                                            height: 250,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'Radar',
                                            theme: 'Sky',
                                            axes: [
                                                {
                                                    type: 'Radial',
                                                    maximum: 100,
                                                    steps: 5,
                                                    position: 'radial'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'radar',
                                                    markerConfig: {
                                                        radius: 4,
                                                        size: 4,
                                                        fill: 'rgb(69,109,159)'
                                                    },
                                                    showMarkers: true,
                                                    style: {
                                                        fill: 'rgb(194,214,240)',
                                                        opacity: 0.5,
                                                        'stroke-width': 0.5
                                                    },
                                                    xField: 'Name',
                                                    yField: 'Data'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'mainContainer',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'listPanel',
                                    collapsible: false,
                                    flex: 1,
                                    region: 'center'
                                },
                                {
                                    xtype: 'detailpanel',
                                    layout: 'fit',
                                    flex: 1,
                                    region: 'south',
                                    split: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'tabContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'tabPanel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onColumnItemMouseUp: function(item) {
        var chart = Ext.ComponentQuery.query('#companyChart')[0],
            grid = Ext.ComponentQuery.query('#companyGridPanel')[0],
            series = chart.series.get(0);

        grid.getSelectionModel().select(Ext.Array.indexOf(series.items, item));
    }

});