/*
 * File: app/view/ListPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ListPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.listPanel',

    requires: [
        'Ext.grid.Panel',
        'Ext.button.Button',
        'Ext.grid.View',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.form.field.Date',
        'Ext.grid.column.Boolean',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Paging'
    ],

    itemId: 'listPanel',
    layout: 'fit',
    title: 'List',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'gridPanel',
                    collapsible: false,
                    titleCollapse: false,
                    columnLines: true,
                    forceFit: true,
                    store: 'SampleDataStore',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'addBtn',
                                    icon: 'resources/images/page_white_add.png',
                                    text: 'Add Record'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'deleteBtn',
                                    icon: 'resources/images/page_white_delete.png',
                                    text: 'Delete Record'
                                }
                            ]
                        }
                    ],
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {

                        })
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            align: 'center',
                            dataIndex: 'id',
                            text: 'Id',
                            flex: 1,
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'title',
                            text: 'Title',
                            flex: 1,
                            editor: {
                                xtype: 'textfield',
                                name: 'title'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'description',
                            text: 'Description',
                            flex: 5,
                            editor: {
                                xtype: 'textfield',
                                name: 'description'
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            align: 'center',
                            dataIndex: 'date',
                            text: 'Date',
                            flex: 1,
                            editor: {
                                xtype: 'datefield',
                                name: 'date'
                            }
                        },
                        {
                            xtype: 'booleancolumn',
                            align: 'center',
                            dataIndex: 'isFeatured',
                            text: 'IsFeatured',
                            flex: 1,
                            editor: {
                                xtype: 'checkboxfield',
                                name: 'isFeatured'
                            }
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'SampleDataStore'
                }
            ]
        });

        me.callParent(arguments);
    }

});