/*
 * File: app/controller/menuController.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.menuController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'centerContainer',
            selector: '#centerContainer'
        },
        {
            ref: 'menuPanel',
            selector: '#menuPanel'
        }
    ],

    menu1: function(button, e, eOpts) {
        //Ext.MessageBox.alert('Msg', 'Btn1 clicked.');
        var menuPanel = this.getMenuPanel();
        var centerContainer = this.getCenterContainer();
        menuPanel.layout.setActiveItem(0);
        centerContainer.layout.setActiveItem(0);

        menuPanel.setTitle('Menu 1');
    },

    menu2: function(button, e, eOpts) {
        var menuPanel = this.getMenuPanel();
        var centerContainer = this.getCenterContainer();
        menuPanel.layout.setActiveItem(1);
        centerContainer.layout.setActiveItem(1);

        menuPanel.setTitle('Menu 2');
    },

    menu3: function(button, e, eOpts) {
        var menuPanel = this.getMenuPanel();
        var centerContainer = this.getCenterContainer();
        menuPanel.layout.setActiveItem(2);
        centerContainer.layout.setActiveItem(2);

        menuPanel.setTitle('Menu 3');
    },

    onMenuitemClick: function(item, e, eOpts) {
        if(item.child() === null) {
            Ext.Msg.alert('Message', Ext.getCmp(item.getItemId()).text + ' selected');
        }
    },

    onTreeViewClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if (record.get('leaf')) {
            Ext.Msg.alert('Msg', record.get('text') + ' selected.');
        }
    },

    onLaunch: function() {
        this.menu1();
    },

    init: function(application) {
        this.control({
            "#menuBtn1": {
                click: this.menu1
            },
            "#menuBtn2": {
                click: this.menu2
            },
            "#menuBtn3": {
                click: this.menu3
            },
            "menuitem": {
                click: this.onMenuitemClick
            },
            "#menuView1, #subMenuView1, #subMenuView2, #subMenuView3": {
                cellclick: this.onTreeViewClick
            }
        });
    }

});
